# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonRpNightly < Formula
  desc "Rusty Photon main application - equipment gateway, event bus, and safety enforcer"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609190924.gd61589b"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-rp-0.1.0+nightly.202609190924.gd61589b-aarch64-apple-darwin.tar.gz"
  sha256 "ff0872f414320c56e65f272e2dc28bb6f8f7c26d1946691f8fcf4e6941f29e73"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-rp",
    because: "both channels install the same rusty-photon-rp binary"

  def install
    bin.install "rusty-photon-rp"
  end

  service do
    run [opt_bin/"rusty-photon-rp"]
    keep_alive true
    log_path var/"log/rusty-photon-rp.log"
    error_log_path var/"log/rusty-photon-rp.log"
  end

  test do
    assert_match "rp", shell_output("#{bin}/rusty-photon-rp --help")
  end
end
