# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPolarAlignNightly < Formula
  desc "Plate-solving polar alignment orchestrator for equatorial mounts"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610011131.g9b16733"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-polar-align-0.1.0+nightly.202610011131.g9b16733-aarch64-apple-darwin.tar.gz"
  sha256 "33d3c03b544493de8a030bbb5c0b6569a52e31d7e8d342309f15a300d9911b91"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-polar-align",
    because: "both channels install the same rusty-photon-polar-align binary"

  def install
    bin.install "rusty-photon-polar-align"
  end

  service do
    run [opt_bin/"rusty-photon-polar-align"]
    keep_alive true
    log_path var/"log/rusty-photon-polar-align.log"
    error_log_path var/"log/rusty-photon-polar-align.log"
  end

  test do
    assert_match "polar-align", shell_output("#{bin}/rusty-photon-polar-align --help")
  end
end
