# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonFocusModelNightly < Formula
  desc "Focus tool provider - sizes, predicts and runs V-curve focus sweeps per optical train through rp, remembering offsets, temperature and every run in a redb store"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609190924.gd61589b"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-focus-model-0.1.0+nightly.202609190924.gd61589b-aarch64-apple-darwin.tar.gz"
  sha256 "47f92598b0dfd062ac44338d28bf87eb44c9ebd9bd895e9757ad1040ef4aa21f"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-focus-model",
    because: "both channels install the same rusty-photon-focus-model binary"

  def install
    bin.install "rusty-photon-focus-model"
  end

  service do
    run [opt_bin/"rusty-photon-focus-model"]
    keep_alive true
    log_path var/"log/rusty-photon-focus-model.log"
    error_log_path var/"log/rusty-photon-focus-model.log"
  end

  test do
    assert_match "focus-model", shell_output("#{bin}/rusty-photon-focus-model --help")
  end
end
