# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSentinelNightly < Formula
  desc "Observatory monitoring and notification service"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609020929.gb743181"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-sentinel-0.1.0+nightly.202609020929.gb743181-aarch64-apple-darwin.tar.gz"
  sha256 "b4282a9c56f13aec36e51b5f94a791d8f418ede22bf50e9bbc5a7f189b144ba1"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-sentinel",
    because: "both channels install the same rusty-photon-sentinel binary"

  def install
    bin.install "rusty-photon-sentinel"
    bin.install "rusty-photon-doctor"
    (prefix/"rusty-photon-renew.plist").write <<~EOS
      <?xml version="1.0" encoding="UTF-8"?>
      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
      <plist version="1.0">
      <dict>
        <key>Label</key>
        <string>space.rustyphoton.renew</string>
        <key>ProgramArguments</key>
        <array>
          <string>#{opt_bin}/rusty-photon-doctor</string>
          <string>tls</string>
          <string>renew</string>
        </array>
        <key>StartCalendarInterval</key>
        <dict>
          <key>Hour</key>
          <integer>3</integer>
          <key>Minute</key>
          <integer>0</integer>
        </dict>
        <key>StandardOutPath</key>
        <string>#{var}/log/rusty-photon-renew.log</string>
        <key>StandardErrorPath</key>
        <string>#{var}/log/rusty-photon-renew.log</string>
      </dict>
      </plist>
    EOS
  end

  service do
    run [opt_bin/"rusty-photon-sentinel"]
    keep_alive true
    log_path var/"log/rusty-photon-sentinel.log"
    error_log_path var/"log/rusty-photon-sentinel.log"
  end

  def caveats
    <<~EOS
      This formula also installs rusty-photon-doctor (the diagnosis and
      repair tool; there is no separate doctor formula). To arm the daily
      TLS renewal job — a no-op until `rusty-photon-doctor tls issue` has
      staged certificates — link and load the bundled launchd plist once
      (the opt path stays valid across upgrades, and launchd only
      auto-loads jobs from the LaunchAgents directory):
        ln -sfv #{opt_prefix}/rusty-photon-renew.plist ~/Library/LaunchAgents/
        launchctl bootstrap gui/$UID ~/Library/LaunchAgents/rusty-photon-renew.plist
      Details: docs/packaging-macos.md in the rusty-photon repo.
    EOS
  end

  test do
    assert_match "sentinel", shell_output("#{bin}/rusty-photon-sentinel --help")
    assert_match "doctor", shell_output("#{bin}/rusty-photon-doctor --help")
  end
end
