# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonRpNightly < Formula
  desc "Rusty Photon main application - equipment gateway, event bus, and safety enforcer"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610071141.g7bf0d82"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-rp-0.1.0+nightly.202610071141.g7bf0d82-aarch64-apple-darwin.tar.gz"
  sha256 "79b2159b950af07c137a65c3ee31579c4c16c408c07a0cea3fd3a2da7547e999"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-rp",
    because: "both channels install the same rusty-photon-rp binary"

  def install
    bin.install "rusty-photon-rp"
  end

  service do
    run [opt_bin/"rusty-photon-rp"]
    keep_alive true
    log_path var/"log/rusty-photon-rp.log"
    error_log_path var/"log/rusty-photon-rp.log"
  end

  test do
    assert_match "rp", shell_output("#{bin}/rusty-photon-rp --help")
  end
end
