# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonStarAdventurerGtiNightly < Formula
  desc "ASCOM Alpaca driver for Sky-Watcher Star Adventurer GTi GEM"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610021101.gc13e5ca"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-star-adventurer-gti-0.1.0+nightly.202610021101.gc13e5ca-aarch64-apple-darwin.tar.gz"
  sha256 "dcf4305acf2cf5122d5ac404ce253012cc393b4dd0e6180f1cf87e99ee4222d2"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-star-adventurer-gti",
    because: "both channels install the same rusty-photon-star-adventurer-gti binary"

  def install
    bin.install "rusty-photon-star-adventurer-gti"
  end

  service do
    run [opt_bin/"rusty-photon-star-adventurer-gti"]
    keep_alive true
    log_path var/"log/rusty-photon-star-adventurer-gti.log"
    error_log_path var/"log/rusty-photon-star-adventurer-gti.log"
  end

  test do
    assert_match "star-adventurer-gti", shell_output("#{bin}/rusty-photon-star-adventurer-gti --help")
  end
end
