# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPaScopsOagNightly < Formula
  desc "ASCOM Alpaca driver for the Pegasus Astro Scops OAG focuser"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609100154.g9380f6d"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-pa-scops-oag-0.1.0+nightly.202609100154.g9380f6d-aarch64-apple-darwin.tar.gz"
  sha256 "51f7499d0dc6e1c82b05f55284a6178b4a61cb3e1d3172f8ce6acbd0127ec06d"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-pa-scops-oag",
    because: "both channels install the same rusty-photon-pa-scops-oag binary"

  def install
    bin.install "rusty-photon-pa-scops-oag"
  end

  service do
    run [opt_bin/"rusty-photon-pa-scops-oag"]
    keep_alive true
    log_path var/"log/rusty-photon-pa-scops-oag.log"
    error_log_path var/"log/rusty-photon-pa-scops-oag.log"
  end

  test do
    assert_match "pa-scops-oag", shell_output("#{bin}/rusty-photon-pa-scops-oag --help")
  end
end
