# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonUpbv2DriverNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Ultimate Powerbox v2"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610101105.ga2ae5d8"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-upbv2-driver-0.1.0+nightly.202610101105.ga2ae5d8-aarch64-apple-darwin.tar.gz"
  sha256 "77dd3340b66b53b272a37f77c752542b9cd8b3cfdc4869619950376b39613601"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-upbv2-driver",
    because: "both channels install the same rusty-photon-upbv2-driver binary"

  def install
    bin.install "rusty-photon-upbv2-driver"
  end

  service do
    run [opt_bin/"rusty-photon-upbv2-driver"]
    keep_alive true
    log_path var/"log/rusty-photon-upbv2-driver.log"
    error_log_path var/"log/rusty-photon-upbv2-driver.log"
  end

  test do
    assert_match "upbv2-driver", shell_output("#{bin}/rusty-photon-upbv2-driver --help")
  end
end
