# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonStarAdventurerGtiNightly < Formula
  desc "ASCOM Alpaca driver for Sky-Watcher Star Adventurer GTi GEM"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610051212.ga540fd1"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-star-adventurer-gti-0.1.0+nightly.202610051212.ga540fd1-aarch64-apple-darwin.tar.gz"
  sha256 "2b734fd5315b4d35a49c7716913de54634806d94d05728e5c24b645668e625c8"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-star-adventurer-gti",
    because: "both channels install the same rusty-photon-star-adventurer-gti binary"

  def install
    bin.install "rusty-photon-star-adventurer-gti"
  end

  service do
    run [opt_bin/"rusty-photon-star-adventurer-gti"]
    keep_alive true
    log_path var/"log/rusty-photon-star-adventurer-gti.log"
    error_log_path var/"log/rusty-photon-star-adventurer-gti.log"
  end

  test do
    assert_match "star-adventurer-gti", shell_output("#{bin}/rusty-photon-star-adventurer-gti --help")
  end
end
