# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPhd2GuiderNightly < Formula
  desc "PHD2 guider client library and service for Rusty Photon"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609010957.g54242af"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-phd2-guider-0.1.0+nightly.202609010957.g54242af-aarch64-apple-darwin.tar.gz"
  sha256 "9b1c0a2ebc1ae7e0e4243c8d8846896050d2007f2f6d23ac822baeac39fe6332"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-phd2-guider",
    because: "both channels install the same rusty-photon-phd2-guider binary"

  def install
    bin.install "rusty-photon-phd2-guider"
  end

  service do
    run [opt_bin/"rusty-photon-phd2-guider"]
    keep_alive true
    log_path var/"log/rusty-photon-phd2-guider.log"
    error_log_path var/"log/rusty-photon-phd2-guider.log"
  end

  test do
    assert_match "phd2-guider", shell_output("#{bin}/rusty-photon-phd2-guider --help")
  end
end
