# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPpbaDriverNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Pocket Powerbox Advance Gen2"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202608311623.g5c8aab7"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-ppba-driver-0.1.0+nightly.202608311623.g5c8aab7-aarch64-apple-darwin.tar.gz"
  sha256 "1c90e5f013f51dd3e2f3b4b6ae6cc8653af5fbd8d0547c8ce9dcec1641482d80"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-ppba-driver",
    because: "both channels install the same rusty-photon-ppba-driver binary"

  def install
    bin.install "rusty-photon-ppba-driver"
  end

  service do
    run [opt_bin/"rusty-photon-ppba-driver"]
    keep_alive true
    log_path var/"log/rusty-photon-ppba-driver.log"
    error_log_path var/"log/rusty-photon-ppba-driver.log"
  end

  test do
    assert_match "ppba-driver", shell_output("#{bin}/rusty-photon-ppba-driver --help")
  end
end
