# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPpbaDriverNightly < Formula
  desc "ASCOM Alpaca driver for Pegasus Astro Pocket Powerbox Advance Gen2"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610041846.g7d6f73b"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-ppba-driver-0.1.0+nightly.202610041846.g7d6f73b-aarch64-apple-darwin.tar.gz"
  sha256 "bb0a3d9cbb83918c2485fa5b457a167a28f8ad854224fc0e8bbc35d35c5d71a9"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-ppba-driver",
    because: "both channels install the same rusty-photon-ppba-driver binary"

  def install
    bin.install "rusty-photon-ppba-driver"
  end

  service do
    run [opt_bin/"rusty-photon-ppba-driver"]
    keep_alive true
    log_path var/"log/rusty-photon-ppba-driver.log"
    error_log_path var/"log/rusty-photon-ppba-driver.log"
  end

  test do
    assert_match "ppba-driver", shell_output("#{bin}/rusty-photon-ppba-driver --help")
  end
end
