# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPolarAlignNightly < Formula
  desc "Plate-solving polar alignment orchestrator for equatorial mounts"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610091148.g694c9f2"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-polar-align-0.1.0+nightly.202610091148.g694c9f2-aarch64-apple-darwin.tar.gz"
  sha256 "b3597ea7f85e5b546d0c5bed5bf4a71a7915fa22934e15985504024ff38b00c6"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-polar-align",
    because: "both channels install the same rusty-photon-polar-align binary"

  def install
    bin.install "rusty-photon-polar-align"
  end

  service do
    run [opt_bin/"rusty-photon-polar-align"]
    keep_alive true
    log_path var/"log/rusty-photon-polar-align.log"
    error_log_path var/"log/rusty-photon-polar-align.log"
  end

  test do
    assert_match "polar-align", shell_output("#{bin}/rusty-photon-polar-align --help")
  end
end
