# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSessionRunnerNightly < Formula
  desc "Generic imaging-workflow orchestrator: executes declarative JSON workflow documents against rp's tool catalog"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609180937.g943d87d"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-session-runner-0.1.0+nightly.202609180937.g943d87d-aarch64-apple-darwin.tar.gz"
  sha256 "6d7a883ad0ec6c2629d0fb0e236f317672f4fe4225d5ffb494a9884ff615c944"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-session-runner",
    because: "both channels install the same rusty-photon-session-runner binary"

  def install
    bin.install "rusty-photon-session-runner"
  end

  service do
    run [opt_bin/"rusty-photon-session-runner"]
    keep_alive true
    log_path var/"log/rusty-photon-session-runner.log"
    error_log_path var/"log/rusty-photon-session-runner.log"
  end

  test do
    assert_match "session-runner", shell_output("#{bin}/rusty-photon-session-runner --help")
  end
end
