# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonFilemonitorNightly < Formula
  desc "File monitoring service for Rusty Photon"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202610021101.gc13e5ca"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-filemonitor-0.1.0+nightly.202610021101.gc13e5ca-aarch64-apple-darwin.tar.gz"
  sha256 "50833b91172f94ff4098db6a2f9ca88f8b82464eecb368353f877a466f86fa55"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-filemonitor",
    because: "both channels install the same rusty-photon-filemonitor binary"

  def install
    bin.install "rusty-photon-filemonitor"
  end

  service do
    run [opt_bin/"rusty-photon-filemonitor"]
    keep_alive true
    log_path var/"log/rusty-photon-filemonitor.log"
    error_log_path var/"log/rusty-photon-filemonitor.log"
  end

  test do
    assert_match "filemonitor", shell_output("#{bin}/rusty-photon-filemonitor --help")
  end
end
