# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPhd2GuiderNightly < Formula
  desc "PHD2 guider client library and service for Rusty Photon"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609061957.g10a37c7"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-phd2-guider-0.1.0+nightly.202609061957.g10a37c7-aarch64-apple-darwin.tar.gz"
  sha256 "4a9e9dc951ecd851d2a52c837e2b5088c2ac33390d72c45db6175b53c841704d"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-phd2-guider",
    because: "both channels install the same rusty-photon-phd2-guider binary"

  def install
    bin.install "rusty-photon-phd2-guider"
  end

  service do
    run [opt_bin/"rusty-photon-phd2-guider"]
    keep_alive true
    log_path var/"log/rusty-photon-phd2-guider.log"
    error_log_path var/"log/rusty-photon-phd2-guider.log"
  end

  test do
    assert_match "phd2-guider", shell_output("#{bin}/rusty-photon-phd2-guider --help")
  end
end
