# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonCalibratorFlatsNightly < Formula
  desc "Flat-field tool provider - trains and takes flats per optical train through rp, remembering the timing in a redb store"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609061607.g5586e76"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-calibrator-flats-0.1.0+nightly.202609061607.g5586e76-aarch64-apple-darwin.tar.gz"
  sha256 "3faff80723e3a774e7246d100953bdb2a11fc7d864219962f1ac814888ab4610"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-calibrator-flats",
    because: "both channels install the same rusty-photon-calibrator-flats binary"

  def install
    bin.install "rusty-photon-calibrator-flats"
  end

  service do
    run [opt_bin/"rusty-photon-calibrator-flats"]
    keep_alive true
    log_path var/"log/rusty-photon-calibrator-flats.log"
    error_log_path var/"log/rusty-photon-calibrator-flats.log"
  end

  test do
    assert_match "calibrator-flats", shell_output("#{bin}/rusty-photon-calibrator-flats --help")
  end
end
