# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonPlanetariumBridgeNightly < Formula
  desc "Virtual ASCOM Alpaca Telescope: planetarium Align gestures become paused rusty-photon targets"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609190924.gd61589b"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-planetarium-bridge-0.1.0+nightly.202609190924.gd61589b-aarch64-apple-darwin.tar.gz"
  sha256 "8573764a1d9a73de41c919c7e0d66edb5c9b4898053730c9720d218d897d67fa"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-planetarium-bridge",
    because: "both channels install the same rusty-photon-planetarium-bridge binary"

  def install
    bin.install "rusty-photon-planetarium-bridge"
  end

  service do
    run [opt_bin/"rusty-photon-planetarium-bridge"]
    keep_alive true
    log_path var/"log/rusty-photon-planetarium-bridge.log"
    error_log_path var/"log/rusty-photon-planetarium-bridge.log"
  end

  test do
    assert_match "planetarium-bridge", shell_output("#{bin}/rusty-photon-planetarium-bridge --help")
  end
end
