# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonZwoCameraNightly < Formula
  desc "ASCOM Alpaca Camera (+ EFW FilterWheel) driver for ZWO ASI hardware"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609030938.gd59d0b9"
  license all_of: [{ any_of: ["MIT", "Apache-2.0"] }, "MIT"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-zwo-camera-0.1.0+nightly.202609030938.gd59d0b9-aarch64-apple-darwin.tar.gz"
  sha256 "5e536cbd7b2247255f72c04a943381507ef07a4b641a93e110eb0010b9e7b002"

  depends_on :macos
  depends_on arch: :arm64
  depends_on "libusb"

  conflicts_with "rusty-photon-zwo-camera",
    because: "both channels install the same rusty-photon-zwo-camera binary"

  def install
    bin.install "rusty-photon-zwo-camera"
    lib.install Dir["lib/*.dylib"]
    doc.install "ZWO-SDK-LICENSE.txt"
  end

  service do
    run [opt_bin/"rusty-photon-zwo-camera"]
    keep_alive true
    log_path var/"log/rusty-photon-zwo-camera.log"
    error_log_path var/"log/rusty-photon-zwo-camera.log"
  end

  test do
    assert_match "zwo-camera", shell_output("#{bin}/rusty-photon-zwo-camera --help")
  end
end
