# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonSkySurveyCameraNightly < Formula
  desc "ASCOM Alpaca Camera simulator backed by NASA SkyView"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609020929.gb743181"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-sky-survey-camera-0.1.0+nightly.202609020929.gb743181-aarch64-apple-darwin.tar.gz"
  sha256 "4cf0895c3f38e006fd7adc7f3abe6067680a6804b93e5c3ed2d9e4d8e8d0a2e2"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-sky-survey-camera",
    because: "both channels install the same rusty-photon-sky-survey-camera binary"

  def install
    bin.install "rusty-photon-sky-survey-camera"
  end

  service do
    run [opt_bin/"rusty-photon-sky-survey-camera"]
    keep_alive true
    log_path var/"log/rusty-photon-sky-survey-camera.log"
    error_log_path var/"log/rusty-photon-sky-survey-camera.log"
  end

  test do
    assert_match "sky-survey-camera", shell_output("#{bin}/rusty-photon-sky-survey-camera --help")
  end
end
