# Generated by scripts/generate-brew-formulas.sh — do not edit in the tap.
class RustyPhotonCalibratorFlatsNightly < Formula
  desc "Flat-field tool provider - trains and takes flats per optical train through rp, remembering the timing in a redb store"
  homepage "https://github.com/rusty-photon/rusty-photon"
  version "0.1.0+nightly.202609100154.g9380f6d"
  license any_of: ["MIT", "Apache-2.0"]
  url "https://github.com/rusty-photon/rusty-photon/releases/download/nightly/rusty-photon-calibrator-flats-0.1.0+nightly.202609100154.g9380f6d-aarch64-apple-darwin.tar.gz"
  sha256 "0a73ac43ce0bae4579c068b816caae359b2b1676b5b7a2df3bc468848bdd9957"

  depends_on :macos
  depends_on arch: :arm64

  conflicts_with "rusty-photon-calibrator-flats",
    because: "both channels install the same rusty-photon-calibrator-flats binary"

  def install
    bin.install "rusty-photon-calibrator-flats"
  end

  service do
    run [opt_bin/"rusty-photon-calibrator-flats"]
    keep_alive true
    log_path var/"log/rusty-photon-calibrator-flats.log"
    error_log_path var/"log/rusty-photon-calibrator-flats.log"
  end

  test do
    assert_match "calibrator-flats", shell_output("#{bin}/rusty-photon-calibrator-flats --help")
  end
end
